src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/manage-connections/manage-connections.component.ts, src/AplosConnector.Web/ClientApp/src/app/services/aplos.service.ts
- More validations on wizard steps
- Only show relevant account types
=> Fix UX issues deferred to phase 2

src/Aplos.Api.Client/AplosApiClient.cs, src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Models/Settings/AppSettingsModel.cs, src/AplosConnector.Common/Services/Abstractions/IAplosIntegrationService.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/Controllers/MappingController.cs, src/AplosConnector.Web/Controllers/SessionController.cs, src/AplosConnector.Web/Models/AplosAuthenticationStatusModel.cs, src/AplosConnector.Web/appsettings.json, tests/AplosConnector.Common.Tests/AplosIntegrationServiceTests.cs, tests/AplosConnector.Web.Tests/SessionControllerTests.cs
[AB#41974](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/41974)
[AB#40691](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/40691)
=> Use PEX's partner credentials

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.ts
Fix issue when a business first logs in post-deployment using client authentication
=> Fix first login issue

src/Aplos.Api.Client/Models/Single/AplosApiPartnerVerificationData.cs, src/Aplos.Api.Client/Models/Single/AplosApiPartnerVerificationDetails.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.SyncWorker/ValidateAplosAccountIds.cs
[AB#42964](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/42964)
=> Fix incorrect Aplos API response structure

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/Controllers/MappingController.cs, src/AplosConnector.Web/Controllers/SessionController.cs, src/AplosConnector.Web/Models/AplosAuthenticationStatusModel.cs
[AB#43023](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/43023)
=> Show friendly error when Aplos Account ID is unknown

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html
Only validate mapping between PEX and Aplos tags when it Aplos tags exist
[AB#43220](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/43220)
=> Fix Aplos tag validation issue

src/Aplos.Api.Client/AplosApiClient.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#43730](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/43730)
=> Only sync expense accounts to tags

src/Aplos.Api.Client/Models/Detail/AplosApiFundDetail.cs, tests/Aplos.Api.Client.Tests/AplosApiClientTests.cs, tests/Aplos.Api.Client.Tests/Samples/Response/GET_funds.json
[AB#43995](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/43995)
=> Support decimals on account number

src/AplosConnector.Web/Startup.cs
[AB#43939](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/43939)
=> Update security headers

src/AplosConnector.Common/Services/AplosIntegrationService.cs, tests/AplosConnector.Common.Tests/AplosIntegrationServiceTests.cs
[AB#44688](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/44688)
=> Fix issue with multiple duplicate account names

src/AplosConnector.Web/ClientApp/package-lock.json
[AB#44855](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/44855)
=> Frontend security fixes

src/AplosConnector.Web/ClientApp/src/app/app.component.html
[AB#46981](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/46981)
=> Update help link

src/AplosConnector.SyncWorker/SyncTimer.cs
- Remove Task.Delay when queueing businesses for processing
- Additional logging
[AB#47405](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/47405)
=> Speed up SyncTimer execution

src/AplosConnector.SyncWorker/TokenRefresher.cs
- Run TokenRefresher twice a day like other PEX Connectors instead of twice an hour\
[AB#47406](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/47406)
=> Run TokenRefresher twice a day

src/Aplos.Api.Client/Abstractions/IAplosApiClient.cs, src/Aplos.Api.Client/Abstractions/IAplosApiClientFactory.cs, src/Aplos.Api.Client/AplosApiClient.cs, src/Aplos.Api.Client/AplosApiClientFactory.cs, src/AplosConnector.Common/Models/Response/AplosServiceAccountModel.cs, src/AplosConnector.Common/Services/Abstractions/IAplosIntegrationService.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Storage/AzureTableStorageAbstract.cs, src/AplosConnector.Common/Storage/Pex2AplosMappingQueue.cs, src/AplosConnector.Common/Storage/Pex2AplosMappingStorage.cs, src/AplosConnector.Common/Storage/PexOAuthSessionStorage.cs, src/AplosConnector.Common/Storage/SyncResultStorage.cs, src/AplosConnector.SyncWorker/PopulateAplosAccountIds.cs, src/AplosConnector.SyncWorker/SyncProcessor.cs, src/AplosConnector.SyncWorker/SyncTimer.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.SyncWorker/ValidateAplosAccountIds.cs, src/AplosConnector.Web/Controllers/AplosController.cs, src/AplosConnector.Web/Controllers/HealthController.cs, src/AplosConnector.Web/Controllers/MappingController.cs, src/AplosConnector.Web/Controllers/PEXController.cs, src/AplosConnector.Web/Controllers/SessionController.cs, tests/AplosConnector.Common.Tests/AplosIntegrationServiceTests.cs, tests/AplosConnector.Web.Tests/SessionControllerTests.cs
[AB#47407](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/47407)
=> Use CancellationToken where possible

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj
[AB#47544](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/47544)
- Upsert tag options (only add) do not remove or disable or change names.
=> US #47544: Upsert Tag Options

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj
[AB#47488](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/47488)
=> PEX SDK 1.11

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#48580](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/48580)
- Log retrieved aplos data (funds, accounts, tags) as JSON to help investigate support issues.
=> Log Aplos Data (Funds, Accounts, Tags) to help investigate support issues.

src/AplosConnector.SyncWorker/TokenRefresher.cs
- Continue processing businesses if an exception occurs for one business
- Enhance logging
- Wait an extra day before attempting to renew PEX tokens
[AB#48708](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/48708)
=> Improve error handling in TokenRefresher

src/AplosConnector.Common/Entities/SyncResultEntity.cs, src/AplosConnector.Common/Models/SyncResultModel.cs, src/AplosConnector.Common/Storage/AzureQueueAbstract.cs, src/AplosConnector.Common/Storage/AzureTableStorageAbstract.cs, src/AplosConnector.Common/Storage/Pex2AplosMappingQueue.cs, src/AplosConnector.Common/Storage/Pex2AplosMappingStorage.cs, src/AplosConnector.Common/Storage/PexOAuthSessionStorage.cs, src/AplosConnector.Common/Storage/SyncResultStorage.cs, src/AplosConnector.SyncWorker/Startup.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.Web/Startup.cs
- Fix issue preventing sync result cleanup
- Only cleanup results older than 1 year
- Reduce unnecessary dependency calls/telemetry
[AB#49275](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/49275)
=> Fix issue preventing sync result cleanup

src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.Web/ClientApp/src/app/app.component.ts, src/AplosConnector.Web/ClientApp/src/app/finish-pex-login/finish-pex-login.component.ts, src/AplosConnector.Web/ClientApp/src/app/handle-pex-jwt/handle-pex-jwt.component.ts, src/AplosConnector.Web/ClientApp/src/app/services/auth.service.ts
- Fix connector login flows [AB#49140](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/49140)
- Logout before login
- Proper usage of observables
=> AB#49140 - Fix Connector Login Flows

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#51591](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/51591)
coalesce start date to y-1
=> #AB51591 - Coalesce start date to Y-1

src/AplosConnector.Common/Services/AplosIntegrationService.cs
#AB51617
- Coalesce start date for business transactions
- Improve log
=> #AB51617 - Coalesce start date to Y-1

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#53753](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/53753)
=> Handle 401 response from Aplos

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#54933](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/54933)
=> Sync ISA fees

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj
=> Aplos - Update PEX SDK

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#55629](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/55629)
- use structured logging scopes when syncing so log events have contextual information of the event (business acct id, cardholder acct id, transaction id, etc).
=> Structured Logging When Syncing

src/Aplos.Api.Client/AplosApiClient.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.SyncWorker/Startup.cs, src/AplosConnector.Web/Startup.cs, tests/AplosConnector.Common.Tests/AplosIntegrationServiceTests.cs
[AB#57712](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/57712)
=> Log Aplos Transaction as JSON When 'Invalid data (bad JSON?)' Error Received

src/AplosConnector.SyncWorker/TokenRefresher.cs
[AB#57816](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/57816)
=> Aplos Connector: Retain sync results for 3 years

src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html
[AB#58543](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/58543)
=> Aplos Connector: Filter additional (ISA) fees for current date range

src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj
[AB#62953](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/62953)
=> 62953 Aplos: Mend security vulnerability (Cryptography xml)

src/AplosConnector.Web/ClientApp/src/app/manage-connections/manage-connections.component.html, src/AplosConnector.Web/ClientApp/src/app/manage-connections/manage-connections.component.ts
[AB#63067](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/63067)
=> 63067 There are no dropdowns for selecting default fund, account and contact for fees (fees)

src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html
[AB#63256](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/63256)
=> 63256 Aplos: UI updates

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.ts
[AB#63292](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/63292)
=> 63292 Credit accounts are pulled as dropdown options for default account value for fees

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/manage-connections/manage-connections.component.html
[AB#63382](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/63382/)
=> 63381 Fees are missing in the name of the "Automatically import PEX purchases with Fund and Account tags and bill payments into Aplos" toggle

src/AplosConnector.SyncWorker/Startup.cs, src/AplosConnector.Web/AplosConnector.Web.csproj, src/AplosConnector.Web/Startup.cs, src/AplosConnector.Web/appsettings.json
[AB#65499](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/65499)
=> Fix DI Registrations

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#65668](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/65668)
=> Improve Sync Results + Syncing

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#65668](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/65668)
=> Fix Transfer Status

src/AplosConnector.Web/Startup.cs
[AB#66894](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/66894)
=> Handle exceptions in POST index.html

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#71766 ](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/71766/)
=> 71766 Aplos: transactions are not synced to Aplos

src/AplosConnector.Web/ClientApp/src/app/services/aplos.service.ts, src/AplosConnector.Web/Controllers/AplosController.cs
[AB#71788 ](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/71788)
=> 71788 Use transactions endpoint

src/AplosConnector.Web/ClientApp/src/app/vendors-manage/vendors-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/vendors-manage/vendors-manage.component.ts, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.html, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.ts, src/AplosConnector.Web/Controllers/AplosController.cs
[AB#71842](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/71842)
=> 71842 Aplos: "Earn 1% rebates on all eligible Vendor card payments." info box is not shown if vendor cards have not been created yet

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Common/Models/PexConnectionDetailModel.cs, src/AplosConnector.Common/VendorCards/VendorCardService.cs, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, src/AplosConnector.Web/ClientApp/src/app/services/pex.service.ts, src/AplosConnector.Web/ClientApp/src/app/vendors-manage/vendors-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.html, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.ts, src/AplosConnector.Web/Controllers/PEXController.cs, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj
[AB#71848](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/71848)
=> 71848 Aplos: "Auto Funding" should be checked by default on the second step of the vendor wizard

src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts, src/AplosConnector.Web/ClientApp/src/app/vendors-manage/vendors-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/vendors-manage/vendors-manage.component.ts, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.css, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.html
[AB#71866](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/71866/)
[AB#71916](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/71916/)
[AB#71910](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/71910/)
=> 71866 Aplos: Add App Notifications

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts
[AB#72017](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/72017/)
[AB#71995](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/71995/)
=> 72017 990 tag issue

src/AplosConnector.Common/Models/Response/BusinessInfo.cs, src/AplosConnector.Common/Models/Response/BusinessNameModel.cs, src/AplosConnector.Web/ClientApp/src/app/app.component.html, src/AplosConnector.Web/ClientApp/src/app/app.component.ts, src/AplosConnector.Web/ClientApp/src/app/services/auth.service.ts, src/AplosConnector.Web/Controllers/SessionController.cs
[AB#72381](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/72381)
=> 72381 Aplos: Help icon for credit business is directing use to Aplos for expense businesses article

src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html
[AB#72382](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/72382)
=> 72382 Latest sync date is shown for new business that has no syncs

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj
[AB#73024](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73024)
=> 73024 Aplos: Mend security vulnerability

src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.html, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.ts
[AB#73832](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73832)
=> 73832 Aplos: Make "Card Limit" field in the Vendor card wizard required

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj, tests/AplosConnector.Web.Tests/AplosConnector.Web.Tests.csproj
[AB#73847](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73847)
=> 73847 Aplos: Mend security vulnerability

src/AplosConnector.Common/Entities/SyncHistoryEntity.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Storage/PexOAuthSessionStorage.cs, src/AplosConnector.Common/Storage/SyncHistoryStorage.cs, src/AplosConnector.SyncWorker/Startup.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.Web/Controllers/SessionController.cs, src/AplosConnector.Web/Startup.cs, tests/AplosConnector.Common.Tests/AplosIntegrationServiceTests.cs
[AB#73899 ](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73899)
=> 73899 Write sync results to SyncHistory table

src/AplosConnector.Common/Storage/AzureTableStorageAbstract.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.SyncWorker/host.json, src/AplosConnector.Web/ClientApp/src/app/sync-history/sync-history.component.ts
[AB#73933](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73933)
=> 73933 Update the TokenRefresher function with the code for copying data.

src/AplosConnector.Common/Storage/AzureTableStorageAbstract.cs, src/AplosConnector.SyncWorker/DataMigration.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs
[AB#73933](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73933)
=> 73933 Create function for copying data

src/AplosConnector.SyncWorker/DataMigration.cs
[AB#73933](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73933/)
=> 73933 Create function for copying data (update)

src/AplosConnector.SyncWorker/Startup.cs
[AB#73933](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/73933/)
=> 73933 Create function for copying data (worker queue fix)

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.css, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
=> #74040 - Normalized Merchant Names

src/AplosConnector.Common/Storage/SyncHistoryStorage.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.Web/Controllers/MappingController.cs
[AB#74062](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/74062)
=> 74062 Switch to SyncHistory table

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.css, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
[AB#74040](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/74040)
=> 74040 - Normalized Merchant Names

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
- [AB#74122](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74122)
- [AB#74125](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74125)
=> Connector Wizard Fixes

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html
[AB#74147](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/74147)
=> 74147 Aplos: contact selection step is not shown for credit business

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
[AB#74216](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/74216)
=> 74216 Aplos: incorrect name of the last step of the connector for credit businesses

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Extensions/CollectionExtensions.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.SyncWorker/SyncTimer.cs, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts, src/AplosConnector.Web/ClientApp/src/app/vendors-select/vendors-select.component.html
[AB#74209](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74209) 
[AB#74218](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74218)
- automatic sync toggle
- minor ui fixes
- fix syncing transfers/fees contact
=> Aplos - Automatic Sync Toggle

src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Web/Controllers/MappingController.cs, src/AplosConnector.Web/Startup.cs
[AB#74320](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74320) [AB#74310](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74310) [AB#74311](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74311) [AB#74218](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/74218)
=> Connector Fixes & Improvements

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Models/PexTransactionExtensions.cs, src/AplosConnector.Common/Models/TimePeriod.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
AB#76239
- post date-time type (transaction or settlement)
=> 76239 - Post Date-Time Type

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.Web/ClientApp/src/app/services/aplos.service.ts, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts
[AB#72145](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/72145)
=> 72145 Update Aplos connector to support rebates

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts
[AB#77441](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77441/)
[AB#77442](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77442/)
[AB#77438](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77438/)
=> 77441 Aplos: "Sync rebates" setting is missing in the "Settings" table on the "Manage sync" tab

src/Aplos.Api.Client/AplosApiClient.cs, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html
[AB#77520](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77520/)
=> 77520 Aplos: not only income and expense accounts are pulled into "Account" dropdown as dropdown options for rebates

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
[AB#77603](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77603)
[AB#77482](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77482)
[AB#77529](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77529)
=> 77603 Aplos: business with enabled 990 tag in Aplos cannot sync rebates

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#77687](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/77687)
changes:
- move some things outside of loops for efficiency (like loading all tags)
- add try/catch/log for each txn/transfer/invoice/fee/rebate we process. so processing doesn't just halt.
- add/improve/remove some logging.
=> 77687 - Connector Sync Efficiency & Exception Handling

src/AplosConnector.Web/ClientApp/src/app/connect/connect.component.html
[AB#78085](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/78085)
=> Clarify wording on launch screen

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-history/sync-history.component.html
[AB#77838](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/77838)
=> 77838 Update Aplos connector to support rebates (Charge)

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts
[AB#78546](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/78546)
=> 78546 UI bugs

src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.html
[AB#78546](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/78546)
=> 78546 UI bugs (990 fix)

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#79800](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/79800)
=> 79800 Fwd: Trouble with PEX Connector to Aplos

src/AplosConnector.SyncWorker/host.json, src/AplosConnector.Web/appsettings.json
[AB#79800](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/79800)
=> 79800 Fwd: Trouble with PEX Connector to Aplos (Log level Warning)

src/AplosConnector.SyncWorker/host.json, src/AplosConnector.Web/appsettings.json
[AB#79800](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/79800)
=> 79800 Fwd: Trouble with PEX Connector to Aplos (Log level Information)

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj
[AB#82221](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/82221)
=> Mend Security Fix

src/Aplos.Api.Client/Aplos.Api.Client.csproj, src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Common/Const/TransactionCategory.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, tests/Aplos.Api.Client.Tests/Aplos.Api.Client.Tests.csproj, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj, tests/AplosConnector.Web.Tests/AplosConnector.Web.Tests.csproj
[AB#84491](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/84491)
=> 84491 Aplos for Charge: Account for business fee trx and cardholder fee trx

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.SyncWorker/Startup.cs, src/AplosConnector.Web/AplosConnector.Web.csproj, src/AplosConnector.Web/Startup.cs, tests/Aplos.Api.Client.Tests/Aplos.Api.Client.Tests.csproj, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj, tests/AplosConnector.Web.Tests/AplosConnector.Web.Tests.csproj
[AB#85125](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/85125)
=> 85125 Aplos: Mend Security vulnerability

src/Aplos.Api.Client/Abstractions/IAplosApiClient.cs, src/Aplos.Api.Client/AplosApiClient.cs, src/AplosConnector.Common/Models/ExpenseAccountMappingModel.cs, src/AplosConnector.Common/Models/TagMappingModel.cs, src/AplosConnector.Common/Services/Abstractions/IAplosIntegrationService.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Web/ClientApp/src/app/services/aplos.service.ts, src/AplosConnector.Web/ClientApp/src/app/services/mapping.service.ts, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.css, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts, src/AplosConnector.Web/ClientApp/src/app/sync-manage/sync-manage.component.ts, src/AplosConnector.Web/Controllers/AplosController.cs
[AB#86908](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/86908)
=> 86908 Aplos: Add tag default option values

src/AplosConnector.Common/Storage/Pex2AplosMappingQueue.cs, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html, src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.ts
[AB#87446](https://pexcard.visualstudio.com/DefaultCollection/Marketplace/_workitems/edit/87446/)
[AB#87443](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/87443/)
=> 87446 Aplos: default tags values are not pulled into "Default" dropdown

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html
[AB#87763](https://pexcard.visualstudio.com/DefaultCollection/Marketplace/_workitems/edit/87763/)
=> 87763 Aplos: default Fund option is required

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj
[AB#87843](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/87843)
=> 87843 Aplos: Mend security vulnerability

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html
[AB#87763](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/87763)
=> 87763 Aplos: default Fund option is required (disabled for Credit)

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj, tests/AplosConnector.Common.Tests/AplosConnector.Common.Tests.csproj, tests/AplosConnector.Web.Tests/AplosConnector.Web.Tests.csproj
[AB#88947](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/88947/)
=> 88947 Aplos: Mend security vulnerabilities

src/AplosConnector.Web/Controllers/MappingController.cs
[AB#91813](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/91813)
Sync Now Cancels When Navigating Away
=> Sync Now Cancels When Navigating Away

src/AplosConnector.Common/AplosConnector.Common.csproj
[AB#92394](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/92394)
[AB#92386](https://pexcard.visualstudio.com/Marketplace/_workitems/edit/92386)
Mend Security
=> Aplos: Mend security vulnerabilities

src/AplosConnector.Common/Services/StorageMappingService.cs
[AB#94899](https://pexcard.visualstudio.com/1e893f43-a87f-46d1-abc4-e68d9e66c1ef/_workitems/edit/94899)
=> Fix field mapping causing manual syncs to not function properly

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.Web/AplosConnector.Web.csproj
[AB#97180](https://pexcard.visualstudio.com/aeed64c4-c884-4a53-8682-73e24201472f/_workitems/edit/97180)
=> override tag option restrictions

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/MappingSettingsModel.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Models/Settings/AppSettingsModel.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj, src/AplosConnector.SyncWorker/Startup.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs, src/AplosConnector.Web/Controllers/PEXController.cs, src/AplosConnector.Web/appsettings.json, src/AplosConnector.sln, src/PexCard.App.Infrastructure.AzureServiceBus/AzureServiceBusSender.cs, src/PexCard.App.Infrastructure.AzureServiceBus/DependencyInjection/ConfigureAzureServiceBusExtensions.cs, src/PexCard.App.Infrastructure.AzureServiceBus/IAzureServiceBusSender.cs, src/PexCard.App.Infrastructure.AzureServiceBus/Messages/EmailTemplateMessage.cs, src/PexCard.App.Infrastructure.AzureServiceBus/Messages/MessageSubjects.cs, src/PexCard.App.Infrastructure.AzureServiceBus/PexCard.App.Infrastructure.AzureServiceBus.csproj
[AB#100942](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/100942)
=> 102237 Aplos: Send Token Expiration Email

src/AplosConnector.SyncWorker/TokenRefresher.cs
[AB#100942](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/100942)
=> 102237 Aplos: Send Token Expiration Email (link)

src/AplosConnector.SyncWorker/TokenRefresher.cs
[AB#100942](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/100942)
=> 102237 Aplos: Send Token Expiration Email (old tokens fix)

src/AplosConnector.Common/Entities/Pex2AplosMappingEntity.cs, src/AplosConnector.Common/Models/Pex2AplosMappingModel.cs, src/AplosConnector.Common/Services/StorageMappingService.cs, src/AplosConnector.SyncWorker/TokenRefresher.cs
[AB#103838](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/103838)
=> 104441 Aplos: Send Token Expiration Email (3 months)

src/AplosConnector.Common/AplosConnector.Common.csproj, src/AplosConnector.Common/Storage/SyncHistoryStorage.cs
[AB#104385](https://pexcard.visualstudio.com/aeed64c4-c884-4a53-8682-73e24201472f/_workitems/edit/104385)
=> 104385 - Fix tag sync history row key issue

src/AplosConnector.Common/Const/PexCardConst.cs, src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#105768](https://pexcard.visualstudio.com/aeed64c4-c884-4a53-8682-73e24201472f/_workitems/edit/105768)
=> 105768 - Improve Synced Notes

src/AplosConnector.Web/ClientApp/src/app/handle-pex-jwt/handle-pex-jwt.component.html, src/AplosConnector.Web/ClientApp/src/app/handle-pex-jwt/handle-pex-jwt.component.ts
[AB#105915](https://pexcard.visualstudio.com/aeed64c4-c884-4a53-8682-73e24201472f/_workitems/edit/105915)
=> Improve JWT transfer component

azure-pipelines.yml
[AB#103253](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/103253)
=> 107446 Aplos Connector: PCI 4.0 - Remove credentials from config files (path fix)

src/AplosConnector.SyncWorker/AplosConnector.SyncWorker.csproj
[AB#103253](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/103253)
=> 107446 Aplos Connector: PCI 4.0 - Remove credentials from config files (missed package)

src/AplosConnector.Web/ClientApp/src/app/sync-connect/sync-connect.component.html
[AB#100290](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/100290)
=> 108781 Aplos: Trim long tag options names to fit table length

src/AplosConnector.Common/Services/AplosIntegrationService.cs
[AB#113314](https://pexcard.visualstudio.com/PEX%20Processing%20Solution/_workitems/edit/113314)
=> 113534 Wesleyan Church of Hamburg: invoice 56607 does not sync to Aplos (additional logging for business)
